const bingoEvents = [
    "Conservative wins a seat in Quebec City",
    "Bloc Québécois loses a stronghold riding",
    "Green Party wins a seat outside BC",
    "Liberals wins in Calgary",
    "Conservatives win less than 5 seats in Atlantic Canada",
    "Maxime Bernier loses his riding",
    "Liberals shut out of Alberta and Saskatchewan",
    "905 region swings decisively to one party",
    "Atlantic provinces go entirely to one party",
    "Saskatchewan goes completely Conservative",
    "Liberals win more than 5 seats in Alberta",
    "Jagmeet Singh loses his riding",
    "Jagmeet Singh wins his riding",
    "Liberals win Ottawa-Centre with a majority",
    "Liberals win Ottawa-Centre with a plurality",
    "NDP wins Ottawa-Centre",
    "NDP shut out west of Ontario",
    "NDP shut out west of Manitoba",
    "NDP wins more than 10 seats",
    "Elizabeth May wins her seat",
    "Elizabeth May loses her seat",
    "NDP shut out in Prairies",
    "Toronto downtown core stays Liberal",
    "Ruth Ellen Brosseau wins her riding",
    "Conservative strength in British Columbia grows",
    "NDP breakthrough in unexpected riding",
    "Bruce Fanjoy wins Carleton",
    "Green Party leader's riding goes down to the wire",
    "An NDP candidate references Tommy Douglas",
    "\"Too early to call\"",
    "\"Statistical tie\"",
    "\"Urban-rural divide\"",
    "\"Bellwether riding\"",
    "\"Political realignment\"",
    "Reference to \"vote efficiency\"",
    "Voter turnout between 60-65%",
    "Voter turnout between 65-70%",
    "Voter turnout between 70-75%",
    "Voter turnout above 75%",
    "Comparison to 2015 election",
    "Comparison to \"NAFTA\" election",
    "Diaspora community referenced as a key demographic",
    "\"Seat rich\"",
    "\"Ground game\"",
    "Discussion of strategic voting",
    "\"Historic shift\"",
    "Reference to American politics",
    "\"Progressive vote split\"",
    "Analyst uses sports metaphor",
    "Reference to Quebec as \"distinct society\"",
    "East to West pipeline",
    "East to West energy grid",
    "Discussion of energy policy",
    "National unity concerns raised",
    "Foreign interference in elections debated",
    "NATO 2% target",
    "Immigrants blamed for housing crisis",
    "\"1 economy not 13\"",
    "Long lines at specific polling stations",
    "Elections Canada website crashes",
    "Analysis of youth turnout",
    "\"Senior voters remain most reliable bloc\"",
    "\"Suburban voters swinging the results\"",
    "\"New Canadians making their voices heard\"",
    "Commentator confuses two party slogans",
    "Multiple party signs visible in background of street interview",
    "Supporter wearing shirt with campaign slogan",
    "Party's French slogan differs meaningfully from English version",
    "Campaign bus with slogan visible in background of broadcast",
    "Analyst notes slogan failed to resonate with voters",
    "Campaign slogan chanted by crowd at headquarters",
    "Mark Carney says \"sustainable prosperity\" in speech",
    "Mark Carney references his international experience",
    "Mark Carney mentions \"fiscal responsibility with compassion\"",
    "Mark Carney references the 2008 financial crisis",
    "Pierre Poilievre says \"axe the tax\" multiple times",
    "Pierre Poilievre mentions \"housing for Canadians\"",
    "Pierre Poilievre attacks \"Carney's banker friends\"",
    "Pierre Poilievre makes a dig at Justin Trudeau",
    "Pierre Poilevre references \"lost liberal decade\"",
    "Jagmeet Singh says \"for people, not profits\"",
    "Jagmeet Singh mentions \"making the ultra-rich pay their fair share\"",
    "Pierre Poilievre wins his riding with over 50% of vote",
    "Pierre Poilievre criticizes \"radical woke left\"",
    "First cabinet speculation begins before results are final",
    "Arctic sovereignty mentioned in leader speech",
    "Pierre Poilievre promises to fire CBC executives",
    "Jagmeet Singh pledges to tax billionaires",
    "Mark Carney mentions \"Canada's place in global economy\"",
    "Analyst references Carney's book \"Value(s)\"",
    "Leader refers to election as a \"referendum on...\"",
    "NDP falls below 10% in national vote",
    "An NDP candidate references Jack Layton",
    "Network doesn't air Maxime Bernier's speech",
    "Elbows up",
    "51st state",
    "Carney discusses \"internal trade barriers\"",
    "\"A clear mandate from the electorate\"",
    "\"A night full of surprises\"",
    "Ballot shortages in certain ridings",
    "Jagmeet Singh says \"The Liberals talk a good game but don't deliver\"",
    "Jagmeet Singh resigns as leader in his speech",
    "A party leader switches between English and French mid-sentence",
    "Reference to Pierre Poilievre not having a top secret security clearance",
    "Reference to Brookfield Asset Management",
    "Host excitedly uses slider tool to show different electoral scenarios",
    "Fancy 3D graphics showing parliament seating arrangements",
    "Broadcaster zooms in dramatically on a specific riding",
    "Analyst plays with graphic display in background of broadcast",
    "Split screen comparison of 2021 vs 2025 results",
    "\"The decision desk is not yet ready to call this riding\"",
    "\"We're seeing some interesting numbers from the decision desk\"",
    "\"The decision desk has seen enough\"",
    "\"Back to you at the decision desk\"",
    "\"The decision desk is monitoring this race closely\"",
    "\"The voters have spoken\"",
    "\"This isn't the result we hoped for\"",
    "\"Our campaign may be over, but our work continues\"",
    "Concession speech mentions \"respecting the democratic process\"",
    "Riding with a gap of less than 100 votes after all polls reporting",
    "Longest Ballot Commission mentioned",
    "Longest ballot blamed for delays in counting Carleton"
];